# Generated by Django 5.0.4 on 2024-04-24 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos_perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tergrasa', models.IntegerField()),
                ('termasa', models.IntegerField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unidades.filial')),
            ],
        ),
    ]
